version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: swift
    directory: /Modules/Observability
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: swift
    directory: /Modules/AudioEngine
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: swift
    directory: /Modules/Persistence
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(deps)"
