import GRDB

/// Phase 7 migration: adds `smart_random_seed` column to `playlists`.
///
/// Smart playlists use this seed for deterministic random ordering that stays
/// stable until the seed is regenerated by the user.
enum M017SmartRandomSeed {
    static func register(in migrator: inout DatabaseMigrator) {
        migrator.registerMigration("017_smart_random_seed") { db in
            try db.execute(
                sql: "ALTER TABLE playlists ADD COLUMN smart_random_seed INTEGER"
            )
            try db.execute(
                sql: """
                UPDATE playlists
                SET smart_random_seed = random()
                WHERE kind = 'smart' AND smart_random_seed IS NULL
                """
            )
        }
    }
}
