#!/usr/bin/env python3
"""Generates docs/data-dictionary.md from a migrated Bòcan SQLite library.

For every table and column in the database it emits a Markdown row with:

  written by   Swift files (outside migrations and tests) that assign the
               column's property, pass it as an init argument, or name the
               column inside an INSERT / UPDATE statement.
  read by      Swift files that reference it without writing it.
  traces to    The migration that introduced the column, unless the curated
               notes file supplies an ADR / issue reference instead.
  notes        Free text from the curated notes file.

The writer / reader split is a grep heuristic, so treat a generated cell as a
lead, not a verdict; the curated notes file is the reviewed layer. Rows whose
"traces to" is only a migration number have not been reviewed.

Usage: gen-data-dictionary.py DB [--source Modules] [--notes docs/data-dictionary-notes.json]
       [--out docs/data-dictionary.md]

`make data-dictionary` runs this against a .backup copy of the real library
(see `make audit-db` for the same pattern) so the schema reflects every
migration the app has applied.
"""

import argparse
import json
import pathlib
import re
import sqlite3

ACRONYMS = {
    "id": "ID", "url": "URL", "json": "JSON", "guid": "GUID", "tls": "TLS", "der": "DER",
    "etag": "ETag", "ms": "MS", "mbid": "MBID", "db": "DB", "hz": "Hz", "html": "HTML",
    "mime": "MIME",
}
IGNORE_TABLES = re.compile(r"^(sqlite_|grdb_)|_fts(_|$)")
EXCLUDE_PATHS = re.compile(r"(Migrations?/|\.build/|/Tests/)")
# GRDB record definitions declare every column (property, init, CodingKey) and
# would otherwise show up as a "writer" of dead columns; they are listed once
# per table instead.
RECORD_PATHS = re.compile(r"/Records/")
MAX_FILES = 5


def camel_variants(snake):
    parts = snake.split("_")
    naive = parts[0] + "".join(p.title() for p in parts[1:])
    aware = parts[0] + "".join(ACRONYMS.get(p, p.title()) for p in parts[1:])
    return {naive, aware}


def classify(name, text):
    """Returns 'write', 'read', or None for one column against one file's text."""
    camels = camel_variants(name)
    any_ref = re.compile(r"\b(" + "|".join(map(re.escape, camels | {name})) + r")\b")
    if not any_ref.search(text):
        return None
    camel_alt = "|".join(map(re.escape, camels))
    assign = re.compile(r"\.(" + camel_alt + r")\s*(=[^=]|\+=|-=)")
    init_arg = re.compile(r"\b(" + camel_alt + r"):\s")
    sql_write = re.compile(
        r"(INSERT[^;]*?\b" + re.escape(name) + r"\b|UPDATE[^;]*?\bSET\b[^;]*?\b" + re.escape(name) + r"\s*=)",
        re.IGNORECASE | re.DOTALL,
    )
    if assign.search(text) or init_arg.search(text) or sql_write.search(text):
        return "write"
    return "read"


def migration_for(name, migrations):
    for path, text in migrations.items():
        if re.search(r"\b" + re.escape(name) + r"\b", text):
            match = re.match(r"M(\d+)", path.name)
            if match:
                return f"M{match.group(1)}"
    return ""


def file_list(paths):
    names = sorted({p.name for p in paths})
    if len(names) > MAX_FILES:
        return ", ".join(names[:MAX_FILES]) + f" (+{len(names) - MAX_FILES})"
    return ", ".join(names)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("db")
    parser.add_argument("--source", default="Modules")
    parser.add_argument("--notes", default="docs/data-dictionary-notes.json")
    parser.add_argument("--out", default="docs/data-dictionary.md")
    args = parser.parse_args()

    source = pathlib.Path(args.source)
    swift = [p for p in source.rglob("*.swift") if not EXCLUDE_PATHS.search(str(p))]
    corpus = {p: p.read_text(errors="replace") for p in swift}
    migrations = {
        p: p.read_text(errors="replace")
        for p in sorted(source.rglob("Migrations/M*.swift"))
    }
    notes = {}
    notes_path = pathlib.Path(args.notes)
    if notes_path.exists():
        notes = json.loads(notes_path.read_text())

    con = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    tables = [
        r[0]
        for r in con.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        if not IGNORE_TABLES.search(r[0])
    ]

    out = []
    out.append("# Data dictionary\n")
    out.append(
        "Generated by `Scripts/gen-data-dictionary.py` (`make data-dictionary`); do not edit the tables by hand. "
        "Curated content lives in `docs/data-dictionary-notes.json` and is merged in on regeneration.\n"
    )
    out.append(
        "**How to read it.** *Written by* and *read by* come from a grep of the Swift sources outside "
        "migrations and tests (a file counts as a writer if it assigns the property, passes it as an "
        "init argument, or names the column in an INSERT / UPDATE). They are leads, not verdicts. "
        "GRDB record files are listed once per table rather than as writers, and single-word column "
        "names (`id`, `name`, `title`) are not grepped at all because they match everything. "
        "*Traces to* is the ADR or issue the column serves; a bare migration number means nobody has "
        "reviewed the row yet. A blank *written by* cell on a populated table is a dead column and "
        "needs an issue (see #414).\n"
    )
    out.append("Schema discipline rules are in `CLAUDE.md`.\n")
    reviewed = unreviewed = 0
    for table in tables:
        out.append(f"\n## `{table}`\n")
        owner = re.compile(r'databaseTableName\s*=\s*"' + re.escape(table) + r'"')
        records = sorted(
            p.name for p, text in corpus.items() if RECORD_PATHS.search(str(p)) and owner.search(text)
        )
        if records:
            out.append("Record: " + ", ".join(f"`{r}`" for r in records) + "\n")
        out.append("| column | type | written by | read by | traces to | notes |")
        out.append("|---|---|---|---|---|---|")
        for _cid, name, ctype, _nn, _dflt, pk in con.execute(f"PRAGMA table_info('{table}')"):
            writers, readers = [], []
            common = "_" not in name
            for path, text in corpus.items():
                if common or RECORD_PATHS.search(str(path)):
                    continue
                verdict = classify(name, text)
                if verdict == "write":
                    writers.append(path)
                elif verdict == "read":
                    readers.append(path)
            note = notes.get(f"{table}.{name}", {})
            traces = note.get("traces") or migration_for(name, migrations)
            if note.get("traces"):
                reviewed += 1
            else:
                unreviewed += 1
            label = f"`{name}`" + (" (pk)" if pk else "")
            w_cell = "n/a (common identifier, see notes)" if common else file_list(writers)
            r_cell = "n/a" if common else file_list(readers)
            out.append(
                f"| {label} | {ctype or ''} | {w_cell} | {r_cell} | "
                f"{traces} | {note.get('note', '')} |"
            )
    out.insert(4, f"Rows reviewed: {reviewed}. Rows with only a migration reference: {unreviewed}.\n")
    pathlib.Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {args.out}: {len(tables)} tables, {reviewed} reviewed rows, {unreviewed} unreviewed")


if __name__ == "__main__":
    main()
